# -*- coding: utf-8 -*-
"""Task02_CS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pdz3-UzKvXjTrc8eAFx_b9nhhi_uI1UW
"""

from PIL import Image
import numpy as np


def encrypt_image(image_path, key):
    image = Image.open(image_path)
    image_array = np.array(image)

    # Encryption: add key and wrap around 255
    encrypted_array = (image_array + key) % 256

    encrypted_image = Image.fromarray(encrypted_array.astype(np.uint8))
    encrypted_image.save("encrypted.png")

    print("🔐 Image encrypted successfully as 'encrypted.png'")


def decrypt_image(image_path, key):
    image = Image.open(image_path)
    image_array = np.array(image)

    # Decryption: subtract key and wrap around 255
    decrypted_array = (image_array - key) % 256

    decrypted_image = Image.fromarray(decrypted_array.astype(np.uint8))
    decrypted_image.save("decrypted.png")

    print("🔓 Image decrypted successfully as 'decrypted.png'")


def main():
    print("===== Image Encryption Tool =====")
    print("1. Encrypt Image")
    print("2. Decrypt Image")

    choice = input("Choose an option (1/2): ")
    image_path = input("Enter image file path: ")
    key = int(input("Enter encryption key (integer): "))

    if choice == "1":
        encrypt_image(image_path, key)
    elif choice == "2":
        decrypt_image(image_path, key)
    else:
        print("❌ Invalid choice.")


if __name__ == "__main__":
    main()